# ancient_translator/transliteration_maps/cypriot_map.py

SCRIPT_NAME = "cypriot"
DESCRIPTION = "Cypriot Syllabary (Deciphered - Phonetic)"
UNICODE_RANGE = ('10800', '1083F') # U+10800 to U+1083F

# Maps Cypriot script characters (keys) to their standard Latin transliterations (values)
TO_LATIN_MAP = {
    # Vowels
    '\U00010800': 'a',    # 𐠀 CYPRIOT SYLLABLE A
    '\U00010801': 'e',    # 𐠁 CYPRIOT SYLLABLE E
    '\U00010802': 'i',    # 𐠂 CYPRIOT SYLLABLE I
    '\U00010803': 'o',    # 𐠃 CYPRIOT SYLLABLE O
    '\U00010804': 'u',    # 𐠄 CYPRIOT SYLLABLE U

    # J-series (or Y-series)
    # Note on U+10806 (je): While defined in Unicode, its attestation in actual Cypriot inscriptions
    # can be rare or debated by some scholars. It's included here as per the Unicode standard.
    # U+10807 (ji - old proposal) and U+10809 (ju - old proposal) are NOT assigned characters.
    '\U00010805': 'ja',   # 𐠅 CYPRIOT SYLLABLE JA (can also be transliterated 'ya')
    '\U00010806': 'je',   # 𐠆 CYPRIOT SYLLABLE JE (can also be transliterated 'ye')
    # U+10807 is unassigned

    # K-series
    '\U00010808': 'ka',   # 𐠈 CYPRIOT SYLLABLE KA
    # U+10809 is unassigned
    '\U0001080A': 'ke',   # 𐠊 CYPRIOT SYLLABLE KE
    '\U0001080B': 'ki',   # 𐠋 CYPRIOT SYLLABLE KI
    '\U0001080C': 'ko',   # 𐠌 CYPRIOT SYLLABLE KO
    '\U0001080D': 'ku',   # 𐠍 CYPRIOT SYLLABLE KU

    # L-series
    '\U0001080E': 'la',   # 𐠎 CYPRIOT SYLLABLE LA
    '\U0001080F': 'le',   # 𐠏 CYPRIOT SYLLABLE LE
    '\U00010810': 'li',   # 𐠐 CYPRIOT SYLLABLE LI
    '\U00010811': 'lo',   # 𐠑 CYPRIOT SYLLABLE LO
    '\U00010812': 'lu',   # 𐠒 CYPRIOT SYLLABLE LU

    # M-series
    '\U00010813': 'ma',   # 𐠓 CYPRIOT SYLLABLE MA
    '\U00010814': 'me',   # 𐠔 CYPRIOT SYLLABLE ME
    '\U00010815': 'mi',   # 𐠕 CYPRIOT SYLLABLE MI
    '\U00010816': 'mo',   # 𐠖 CYPRIOT SYLLABLE MO
    '\U00010817': 'mu',   # 𐠗 CYPRIOT SYLLABLE MU

    # N-series
    '\U00010818': 'na',   # 𐠘 CYPRIOT SYLLABLE NA
    '\U00010819': 'ne',   # 𐠙 CYPRIOT SYLLABLE NE
    '\U0001081A': 'ni',   # 𐠚 CYPRIOT SYLLABLE NI
    '\U0001081B': 'no',   # 𐠛 CYPRIOT SYLLABLE NO
    '\U0001081C': 'nu',   # 𐠜 CYPRIOT SYLLABLE NU

    # X-series (representing /ks/)
    '\U0001081D': 'xa',   # 𐠝 CYPRIOT SYLLABLE XA (ks-a)
    '\U0001081E': 'xe',   # 𐠞 CYPRIOT SYLLABLE XE (ks-e)
    # U+1081F XI is unassigned in current Unicode standard
    '\U00010820': 'xo',   # 𐠠 CYPRIOT SYLLABLE XO (ks-o)
    # U+10821 XU is unassigned

    # P-series
    '\U00010822': 'pa',   # 𐠢 CYPRIOT SYLLABLE PA
    '\U00010823': 'pe',   # 𐠣 CYPRIOT SYLLABLE PE
    '\U00010824': 'pi',   # 𐠤 CYPRIOT SYLLABLE PI
    '\U00010825': 'po',   # 𐠥 CYPRIOT SYLLABLE PO
    '\U00010826': 'pu',   # 𐠦 CYPRIOT SYLLABLE PU

    # R-series
    '\U00010827': 'ra',   # 𐠧 CYPRIOT SYLLABLE RA
    '\U00010828': 're',   # 𐠨 CYPRIOT SYLLABLE RE
    '\U00010829': 'ri',   # 𐠩 CYPRIOT SYLLABLE RI
    '\U0001082A': 'ro',   # 𐠪 CYPRIOT SYLLABLE RO
    '\U0001082B': 'ru',   # 𐠫 CYPRIOT SYLLABLE RU

    # S-series
    '\U0001082C': 'sa',   # 𐠬 CYPRIOT SYLLABLE SA
    '\U0001082D': 'se',   # 𐠭 CYPRIOT SYLLABLE SE
    '\U0001082E': 'si',   # 𐠮 CYPRIOT SYLLABLE SI
    '\U0001082F': 'so',   # 𐠯 CYPRIOT SYLLABLE SO
    '\U00010830': 'su',   # 𐠰 CYPRIOT SYLLABLE SU

    # T-series
    '\U00010831': 'ta',   # 𐠱 CYPRIOT SYLLABLE TA
    '\U00010832': 'te',   # 𐠲 CYPRIOT SYLLABLE TE
    '\U00010833': 'ti',   # 𐠳 CYPRIOT SYLLABLE TI
    '\U00010834': 'to',   # 𐠴 CYPRIOT SYLLABLE TO
    '\U00010835': 'tu',   # 𐠵 CYPRIOT SYLLABLE TU

    # W-series (representing /w/ or /v/)
    '\U00010836': 'wa',   # 𐠶 CYPRIOT SYLLABLE WA (or va)
    '\U00010837': 'we',   # 𐠷 CYPRIOT SYLLABLE WE (or ve)
    '\U00010838': 'wi',   # 𐠸 CYPRIOT SYLLABLE WI (or vi)

    # Z-series (representing /dz/ or /ts/ initially, later perhaps /z/)
    '\U0001083B': 'za',   # 𐠻 CYPRIOT SYLLABLE ZA
    # U+1083C ZE is unassigned
    # U+1083D ZO is unassigned

    # Punctuation / Other
    # U+1083E is unassigned
    '\U0001083F': '.',    # 𐠿 CYPRIOT SYLLABLE PUNCTUATOR (Often used as a word separator. Transliterated as '.' or a space depending on convention.)
}

# The FROM_LATIN_MAP will be automatically generated by your __init__.py
# FROM_LATIN_MAP = {v: k for k, v in TO_LATIN_MAP.items()}